services:

  storage:
    image: storage
    container_name: storage
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: ["sh", "-c", "python3 app/main.py"]
    volumes:
      - ".:/app"

  