[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyyel-cloudops"
version = "0.0.2"
description = "Deployment tools"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name="Nayel BLIDI", email="nayel.blidi@gmail.com" }
]
dependencies = [
    "boto3",
    "mysql-connector-python",
    "tqdm",
    "elasticsearch",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]
